### ISSUE TITLE
파일등록 오류 ?

### ISSUE THREAD

**Issue by JungsupOh** [ssj24/finger-express#14]
[음성녹음샘플.zip](https://github.com/ssj24/finger-express/files/10467140/default.zip)

상기 2개의 파일을 가지고 동시에 업로드 하는것 테스트 하는데..

미리보기에서, '등록하기' 누르면 계속 로딩중 만 나옴..

아마도 wav 파일이 문제가 있는 듯 합니다.

**Comment by ssj24** [comment]
오류시 알림이 뜨게 했습니다
