### ISSUE TITLE
장바구니가 비어있을 때?

### ISSUE THREAD

**Issue by JungsupOh** [ssj24/finger-express#15]
로그인 후, 곧바로 장바구니로 들어가면,

비어있는 장바구니가 나타나야하며, 

장바구니가 비어있을때에는 주소라던지, 구매예정아이템이 없는게 자연스러울듯 합니다.

**Comment by ssj24** [comment]
회원가입 후 바로 장바구니에 들어갔을 때는 장바구니와 주소 모두 비어있고
주문을 한 차례 진행했을 때에는 정보가 저장이 되어서 장바구니가 비어 있어도 주소가 입력이 되어 있는데
주문을 진행한 사용자여도 장바구니에 아이템이 없을 때는 주소가 입력이 안 되어 있어야 한다는 말씀이신 거죠?
구매예정아이템은 무엇인가요? 지금 장바구니가 비어있으면 구매예정아이템이 보이시나요?

**Comment by ssj24** [comment]
수정했습니다
