### ISSUE TITLE
디자인 적용

### ISSUE THREAD

**Issue by JungsupOh** [ssj24/finger-express#7]
https://www.figma.com/file/fe4b3kftbmIBvvsw3L5WxJ/finger.exp-(%EC%B5%9C%EC%A2%85%EB%B3%B8)?node-id=0%3A1&t=FMyrYQ5hCQTo3vsA-1

상기 피그마 파일을 참고하여 디자인 적용

1) 메인화면
2) 파일 추가시, 첨부파일 버튼
3) 자동 미리보기 생성

**Comment by ssj24** [comment]
수정했습니다
